[package]
name = "stagbin"
version = "0.2.0"
edition = "2021"

[dependencies]
structopt = "0.3.25"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1.0", features= ["derive"]}
serde_json = {version = "1.0"}
tokio = {version = "1", features = ["full"]}